In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
extrait1=pd.read_excel('LFB Incident data Last 3 years.xlsx')
colnames1=pd.Series(extrait1.columns)

0                             IncidentNumber
1                                 DateOfCall
2                                    CalYear
3                                 TimeOfCall
4                                 HourOfCall
5                              IncidentGroup
6                        StopCodeDescription
7                         SpecialServiceType
8                           PropertyCategory
9                               PropertyType
10                          AddressQualifier
11                             Postcode_full
12                         Postcode_district
13                                      UPRN
14                                      USRN
15                        IncGeo_BoroughCode
16                        IncGeo_BoroughName
17                                ProperCase
18                           IncGeo_WardCode
19                           IncGeo_WardName
20                        IncGeo_WardNameNew
21                                 Easting_m
22                                Northing_m
23                           Easting_rounded
24                          Northing_rounded
25                                  Latitude
26                                 Longitude
27                                       FRS
28                     IncidentStationGround
29          FirstPumpArriving_AttendanceTime
30     FirstPumpArriving_DeployedFromStation
31         SecondPumpArriving_AttendanceTime
32    SecondPumpArriving_DeployedFromStation
33             NumStationsWithPumpsAttending
34                         NumPumpsAttending
35                                 PumpCount
36                          PumpHoursRoundUp
37                         Notional Cost (£)
dtype: object

In [4]:
data=pd.read_csv('LFB Incident data - Datastore - with notional cost and UPRN from January 2009.csv',names=colnames1)

C:\Users\ludo\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [7]:
data.head()

,IncidentNumber,DateOfCall,CalYear,TimeOfCall,HourOfCall,IncidentGroup,StopCodeDescription,SpecialServiceType,PropertyCategory,PropertyType,AddressQualifier,Postcode_full,Postcode_district,UPRN,USRN,IncGeo_BoroughCode,IncGeo_BoroughName,ProperCase,IncGeo_WardCode,IncGeo_WardName,IncGeo_WardNameNew,Easting_m,Northing_m,Easting_rounded,Northing_rounded,Latitude,Longitude,FRS,IncidentStationGround,FirstPumpArriving_AttendanceTime,FirstPumpArriving_DeployedFromStation,SecondPumpArriving_AttendanceTime,SecondPumpArriving_DeployedFromStation,NumStationsWithPumpsAttending,NumPumpsAttending,PumpCount,PumpHoursRoundUp,Notional Cost (£)
0,235138081,01 Jan 2009,2009,00:00:37,0,Special Service,Special Service,RTC,Road Vehicle,Car,In street close to gazetteer location,SW11 4LB,SW11,NaN,NaN,E09000032,WANDSWORTH,Wandsworth,E05000620,Queenstown,Queenstown,528652.0,176830.0,528650,176850,51.475812,-0.148894,London,Battersea,319.0,Battersea,342.0,Clapham,2.0,2.0,2.0,1.0,255.0
1,1091,01 Jan 2009,2009,00:00:46,0,Special Service,Special Service,Assist other agencies,Outdoor,Lake/pond/reservoir,Open land/water - nearest gazetteer location,SE1 7SG,SE1,NaN,NaN,E09000022,LAMBETH,Lambeth,E05000416,Bishop's,Bishop's,530485.0,179007.0,530450,179050,51.494957,-0.121712,London,Lambeth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2091,01 Jan 2009,2009,00:03:00,0,Fire,Secondary Fire,NaN,Outdoor,Road surface/pavement,In street outside gazetteer location,N9 9EL,N9,NaN,NaN,E09000010,ENFIELD,Enfield,E05000201,Haselbury,Haselbury,533773.0,194492.0,533750,194450,51.633342,-0.068488,London,Edmonton,308.0,Edmonton,NaN,NaN,1.0,1.0,1.0,1.0,255.0
3,3091,01 Jan 2009,2009,00:04:27,0,Fire,Secondary Fire,NaN,Outdoor,Domestic garden (vegetation not equipment),On land associated with building,UB10 0DG,UB10,1.000215e+11,21401491.0,E09000017,HILLINGDON,Hillingdon,E05000332,Hillingdon East,Hillingdon East,507738.0,182805.0,507750,182850,51.533882,-0.448089,London,Hillingdon,210.0,Hillingdon,NaN,NaN,1.0,1.0,1.0,1.0,255.0
4,5091,01 Jan 2009,2009,00:05:39,0,Fire,Secondary Fire,NaN,Outdoor,Cycle path/public footpath/bridleway,In street outside gazetteer location,N7 8HG,N7,NaN,NaN,E09000019,ISLINGTON,Islington,E05000375,Holloway,Holloway,531058.0,185307.0,531050,185350,51.551441,-0.111120,London,Holloway,233.0,Holloway,250.0,Holloway,1.0,2.0,2.0,1.0,255.0

In [6]:
data = data.infer_objects()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1388197 entries, 0 to 1388196
Data columns (total 38 columns):
 #   Column                                  Non-Null Count    Dtype
---  ------                                  --------------    -----
 0   IncidentNumber                          1388197 non-null  object
 1   DateOfCall                              1388197 non-null  object
 2   CalYear                                 1388197 non-null  int64
 3   TimeOfCall                              1388197 non-null  object
 4   HourOfCall                              1388197 non-null  int64
 5   IncidentGroup                           1388197 non-null  object
 6   StopCodeDescription                     1388197 non-null  object
 7   SpecialServiceType                      430734 non-null   object
 8   PropertyCategory                        1388197 non-null  object
 9   PropertyType                            1388197 non-null  object
 10  AddressQualifier                        1388197 non-null  object
 11  Postcode_full                           725271 non-null   object
 12  Postcode_district                       1388197 non-null  object
 13  UPRN                                    1246864 non-null  float64
 14  USRN                                    1225326 non-null  float64
 15  IncGeo_BoroughCode                      1388197 non-null  object
 16  IncGeo_BoroughName                      1388197 non-null  object
 17  ProperCase                              1388197 non-null  object
 18  IncGeo_WardCode                         1388196 non-null  object
 19  IncGeo_WardName                         1388196 non-null  object
 20  IncGeo_WardNameNew                      1388196 non-null  object
 21  Easting_m                               725271 non-null   float64
 22  Northing_m                              725271 non-null   float64
 23  Easting_rounded                         1388197 non-null  int64
 24  Northing_rounded                        1388197 non-null  int64
 25  Latitude                                725271 non-null   float64
 26  Longitude                               725271 non-null   float64
 27  FRS                                     1388197 non-null  object
 28  IncidentStationGround                   1388197 non-null  object
 29  FirstPumpArriving_AttendanceTime        1272805 non-null  float64
 30  FirstPumpArriving_DeployedFromStation   1272795 non-null  object
 31  SecondPumpArriving_AttendanceTime       498503 non-null   float64
 32  SecondPumpArriving_DeployedFromStation  498497 non-null   object
 33  NumStationsWithPumpsAttending           1378473 non-null  float64
 34  NumPumpsAttending                       1378473 non-null  float64
 35  PumpCount                               1380786 non-null  float64
 36  PumpHoursRoundUp                        1380537 non-null  float64
 37  Notional Cost (£)                       1380537 non-null  float64
dtypes: float64(13), int64(4), object(21)
memory usage: 402.5+ MB

In [8]:
extrait2=pd.read_excel('LFB Mobilisation data Last 3 years.xlsx',nrows=5)
colnames2=pd.Series(extrait2.columns)

In [14]:
data2=pd.read_csv('LFB Mobilisation data from January 2009.csv',names=colnames2)

C:\Users\ludo\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (0,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [15]:
data2 = data2.infer_objects()
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1916074 entries, 0 to 1916073
Data columns (total 22 columns):
 #   Column                    Dtype
---  ------                    -----
 0   IncidentNumber            object
 1   CalYear                   int64
 2   HourOfCall                int64
 3   ResourceMobilisationId    int64
 4   Resource_Code             object
 5   PerformanceReporting      object
 6   DateAndTimeMobilised      object
 7   DateAndTimeMobile         object
 8   DateAndTimeArrived        object
 9   TurnoutTimeSeconds        float64
 10  TravelTimeSeconds         float64
 11  AttendanceTimeSeconds     int64
 12  DateAndTimeLeft           object
 13  DateAndTimeReturned       object
 14  DeployedFromStation_Code  object
 15  DeployedFromStation_Name  object
 16  DeployedFromLocation      object
 17  PumpOrder                 int64
 18  PlusCode_Code             object
 19  PlusCode_Description      object
 20  DelayCodeId               float64
 21  DelayCode_Description     object
dtypes: float64(3), int64(5), object(14)
memory usage: 321.6+ MB

In [25]:
data.isna().sum()

IncidentNumber                                 0
DateOfCall                                     0
CalYear                                        0
TimeOfCall                                     0
HourOfCall                                     0
IncidentGroup                                  0
StopCodeDescription                            0
SpecialServiceType                        957463
PropertyCategory                               0
PropertyType                                   0
AddressQualifier                               0
Postcode_full                             662926
Postcode_district                              0
UPRN                                      141333
USRN                                      162871
IncGeo_BoroughCode                             0
IncGeo_BoroughName                             0
ProperCase                                     0
IncGeo_WardCode                                1
IncGeo_WardName                                1
IncGeo_WardNameNew                             1
Easting_m                                 662926
Northing_m                                662926
Easting_rounded                                0
Northing_rounded                               0
Latitude                                  662926
Longitude                                 662926
FRS                                            0
IncidentStationGround                          0
FirstPumpArriving_AttendanceTime          115392
FirstPumpArriving_DeployedFromStation     115402
SecondPumpArriving_AttendanceTime         889694
SecondPumpArriving_DeployedFromStation    889700
NumStationsWithPumpsAttending               9724
NumPumpsAttending                           9724
PumpCount                                   7411
PumpHoursRoundUp                            7660
Notional Cost (£)                           7660
dtype: int64

In [27]:
data.duplicated().value_counts()

False    1388197
dtype: int64

In [29]:
data.DateOfCall=pd.to_datetime(data.DateOfCall)

In [30]:
data.DateOfCall

,IncidentNumber,DateOfCall,CalYear,TimeOfCall,HourOfCall,IncidentGroup,StopCodeDescription,SpecialServiceType,PropertyCategory,PropertyType,AddressQualifier,Postcode_full,Postcode_district,UPRN,USRN,IncGeo_BoroughCode,IncGeo_BoroughName,ProperCase,IncGeo_WardCode,IncGeo_WardName,IncGeo_WardNameNew,Easting_m,Northing_m,Easting_rounded,Northing_rounded,Latitude,Longitude,FRS,IncidentStationGround,FirstPumpArriving_AttendanceTime,FirstPumpArriving_DeployedFromStation,SecondPumpArriving_AttendanceTime,SecondPumpArriving_DeployedFromStation,NumStationsWithPumpsAttending,NumPumpsAttending,PumpCount,PumpHoursRoundUp,Notional Cost (£)
0,235138081,2009-01-01,2009,00:00:37,0,Special Service,Special Service,RTC,Road Vehicle,Car,In street close to gazetteer location,SW11 4LB,SW11,NaN,NaN,E09000032,WANDSWORTH,Wandsworth,E05000620,Queenstown,Queenstown,528652.0,176830.0,528650,176850,51.475812,-0.148894,London,Battersea,319.0,Battersea,342.0,Clapham,2.0,2.0,2.0,1.0,255.0
1,1091,2009-01-01,2009,00:00:46,0,Special Service,Special Service,Assist other agencies,Outdoor,Lake/pond/reservoir,Open land/water - nearest gazetteer location,SE1 7SG,SE1,NaN,NaN,E09000022,LAMBETH,Lambeth,E05000416,Bishop's,Bishop's,530485.0,179007.0,530450,179050,51.494957,-0.121712,London,Lambeth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2091,2009-01-01,2009,00:03:00,0,Fire,Secondary Fire,NaN,Outdoor,Road surface/pavement,In street outside gazetteer location,N9 9EL,N9,NaN,NaN,E09000010,ENFIELD,Enfield,E05000201,Haselbury,Haselbury,533773.0,194492.0,533750,194450,51.633342,-0.068488,London,Edmonton,308.0,Edmonton,NaN,NaN,1.0,1.0,1.0,1.0,255.0
3,3091,2009-01-01,2009,00:04:27,0,Fire,Secondary Fire,NaN,Outdoor,Domestic garden (vegetation not equipment),On land associated with building,UB10 0DG,UB10,1.000215e+11,21401491.0,E09000017,HILLINGDON,Hillingdon,E05000332,Hillingdon East,Hillingdon East,507738.0,182805.0,507750,182850,51.533882,-0.448089,London,Hillingdon,210.0,Hillingdon,NaN,NaN,1.0,1.0,1.0,1.0,255.0
4,5091,2009-01-01,2009,00:05:39,0,Fire,Secondary Fire,NaN,Outdoor,Cycle path/public footpath/bridleway,In street outside gazetteer location,N7 8HG,N7,NaN,NaN,E09000019,ISLINGTON,Islington,E05000375,Holloway,Holloway,531058.0,185307.0,531050,185350,51.551441,-0.111120,London,Holloway,233.0,Holloway,250.0,Holloway,1.0,2.0,2.0,1.0,255.0